INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (1, N'Nike');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (2, N'Adidas');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (3, N'Apple');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (4, N'Samsung');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (5, N'Sony');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (6, N'Google');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (7, N'Microsoft');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (8, N'Coca-Cola');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (9, N'Toyota');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (10, N'BMW');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (11, N'Zara');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (12, N'H&M');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (13, N'GAP');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (14, N'Forever 21');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (15, N'Uniqlo');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (16, N'Levi Strauss & Co.');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (17, N'Calvin Klein');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (18, N'Tommy Hilfiger');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (19, N'Ralph Lauren');
INSERT INTO Outnet.dbo.Brand (brand_id, name) VALUES (20, N'Under Armour');
