INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Nike');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Adidas');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Apple');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Samsung');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Sony');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Google');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Microsoft');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Coca-Cola');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Toyota');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'BMW');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Zara');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'H&M');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'GAP');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Forever 21');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Uniqlo');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Levi Strauss & Co.');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Calvin Klein');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Tommy Hilfiger');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Ralph Lauren');
INSERT INTO Outnet.dbo.Brand (name) VALUES (N'Under Armour');
